### ISSUE TITLE
[issue] 피어의 연결이 간혈적으로 끊기는 에러

### ISSUE THREAD

**Issue by Yanguk** [Team-TTT/Circle-Service-FE#6]
피어의 연결이 간혈적으로 끊기는 에러는 어떻게 처리하면 좋을까요

#5 
순서를 보장시켜주면 되는것일까?

#13 
* `Failed to execute 'setLocalDescription' on 'RTCPeerConnection` 이라는 에러가 관건인데
서치 결과 크롬브라우저만의 버그 문제 일수도있음. 아직 해결방안을 모르겠음

위 에러가 콜러 한테 발생하면 밑에 에러는 콜리한테 발생함

* `Connection failed. at Peer._onConnectionStateChange`

---

참고자료
https://velog.io/@njw1204/WebRTC-간헐적-연결-실패-문제-해결

**Comment by ssong-yi** [comment]
현재로선 끊길 때마다 저희가 새로고침하는 대신,
논의할 때 나왔던 얘기처럼 에러가 나면 `redirect`해주도록 처리하는 게 좋지 않을까요?

**Comment by Yanguk** [comment]
simple-peer 라이브러리를 사용하지 않아야할까요?

**Comment by Yanguk** [comment]
stun/turn 서버의 문제 일수도 있습니다

**Comment by ssong-yi** [comment]
`NAT(Network Address Translation)`을 통과하지 못하거나 방화벽으로 인해 직접 연결이 실패하는 경우, `WebRTC` `ICE`는 `TURN`서버를 사용합니다. 즉, `STUN` 서버에서 피어 연결을 실패할 경우, `TURN` 서버를 사용해 피어를 연결합니다.
`simple-peer`에선 `peer`생성자에 `config`옵션을 지정해줘서 `TURN` 서버를 사용할 수 있도록 했습니다.

참고링크: [simple-peer 문서](https://github.com/feross/simple-peer#connection-does-not-work-on-some-networks)
